apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/lib/loki/index
        cache_location: /var/lib/loki/cache
        resync_interval: 5s
        shared_store: filesystem
      filesystem:
        directory: /var/lib/loki/chunks
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /var/lib/loki/compactor
      shared_store: filesystem
    ingester:
      wal:
        dir: /var/lib/loki/wal